"""
Django settings for psiproject project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from os.path import abspath, dirname, join

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = dirname(dirname(dirname(abspath(__file__))))

SECRET_KEY = os.environ.get('SECRET_KEY',
                            'please-set-a-secret-secret-key')

PSI_DATA_DIRECTORY_PATH = os.environ.get(\
                                'PSI_DATA_DIRECTORY_PATH',
                                join(BASE_DIR, 'data'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/


AUTH_USER_MODEL = 'psi_auth.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'psi_apps',
    'psi_apps.flask_services',
    'psi_apps.content_pages',
    'psi_apps.psi_auth',
    'webpack_loader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'psiproject.urls'

LOGIN_REDIRECT_URL = 'interface'
LOGOUT_REDIRECT_URL = 'login'

TEMPLATES_DIR = join(BASE_DIR, 'templates')
FRONTEND_DIR = join(BASE_DIR, 'frontend')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'psiproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
TEST_DIRECT_STATIC = join(BASE_DIR, 'frontend')

STATICFILES_DIRS = [
    FRONTEND_DIR,
]

WEBPACK_LOADER = {
    'DEFAULT': {
        # 'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': 'dist/',  # must end with slash
        'STATS_FILE': os.path.join(BASE_DIR, 'frontend', 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'TIMEOUT': None,
        'IGNORE': [r'.+\.hot-update.js', r'.+\.map']
    }
}


def add_backslash(name, val):
    assert val, 'val for %s must be set' % name
    if val[-1] != '/':
        val += '/'
    return val.strip()

# --------------------------------------------------
# Url for the actual flask server
# --------------------------------------------------
FLASK_SERVER_BASE = os.environ.get('FLASK_SERVER_BASE',
                                  'http://0.0.0.0:8000/')
add_backslash('FLASK_SERVER_BASE', FLASK_SERVER_BASE)

# --------------------------------------------------
# Used by the UI, routes through django or nginx->django
#
#  Example values: "/custom/", "http://psiproject.org/flask-custom/
# --------------------------------------------------
FLASK_SVC_URL = os.environ.get('FLASK_SVC_URL',
                              '/flask-custom/')
add_backslash('FLASK_SVC_URL', FLASK_SVC_URL)

PAGE_CACHE_TIME = 0 # dev time


EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")
