# Generated by Django 2.0.8 on 2019-02-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creators', models.TextField()),
                ('file_name', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
