# Generated by Django 2.0.8 on 2019-02-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_dataset_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='permission',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
