# Generated by Django 2.0.8 on 2019-03-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0003_auto_20190226_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='file_name',
            new_name='json_file',
        ),
        migrations.AddField(
            model_name='dataset',
            name='xml_file',
            field=models.TextField(default='default.xml'),
            preserve_default=False,
        ),
    ]
